name: Deploy Docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip --version

      - name: Install Hatch
        run: |
          pipx install --verbose hatch
          hatch --version

      - name: Build documentation
        run: |
          hatch run docs:build

      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4
